apiVersion: v1
kind: Namespace
metadata:
  name: trust-safety
  labels:
    app.kubernetes.io/name: adult-platform-trust-safety
    app.kubernetes.io/part-of: adult-platform-trust-safety
    environment: production
